# Generated by Django 3.0.5 on 2020-12-27 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replays', '0001_squashed_0004_auto_20201226_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replay',
            name='file',
            field=models.FileField(upload_to='replays'),
        ),
    ]
